version: '3.3'
services:
  web:
    image: tubes-1-wbd:latest
    ports:
      - 8080:80
    hostname: tubes-1-wbd-hostname
    env_file: .env
    volumes:
      - ./src:/var/www/html
  mysql:
    image: mysql:latest
    ports:
      - 3307:3306
    hostname: db-tubes-1
    env_file: .env
    volumes:
      - ./mysql:/var/lib/mysql
networks:
  web-mysql:
    driver: bridge  