version: '3.3'
services:
  web:
    image: tubes-1-wbd:latest
    ports:
      - 8080:80
    hostname: tubes-1-wbd-hostname
    env_file: .env
    volumes:
      - ./src:/var/www/html
  db:
    container_name: db-tubes-1
    image: mysql:5.7
    restart: unless-stopped
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
    command: mysqld --init-file="/docker-entrypoint-initdb.d/init_db.sql"
    env_file:
      - .env
    ports:
      - "3308:3308" 
  mysql:
    image: mysql:latest
    ports:
      - 3310:3309
    hostname: db-tubes-1
    env_file: .env
    volumes:
      - ./mysql:/var/lib/mysql

networks:
  web-mysql:
    driver: bridge
